version: "3.8"
services:
  # Redis
  redis:
    restart: always
    image: redis:5
    container_name: fbrq-redis
    volumes:
      - redis-data:/var/lib/redis
    ports:
      - "6378:6379"
    networks:
      - fbrq-net
    # Postgres
  postgres:
    restart: always
    image: postgres:13
    container_name: fbrq-postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: fabrique_db
    ports:
      - "5431:5432"
    networks:
      - fbrq-net
  # Django Server
  server:
    restart: always
    container_name: fbrq-server
    build:
      context: ./
      dockerfile: ./deploy/docker/server.Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    networks:
      - fbrq-net
  # Celery Worker & Beat
  celery:
    restart: always
    container_name: fbrq-celery
    build:
      context: ./
      dockerfile: ./deploy/docker/celery.Dockerfile
    volumes:
      - redis-data:/var/lib/redis/
    depends_on:
      - redis
      - postgres
      - server
    networks:
      - fbrq-net

networks:
  fbrq-net:
    driver: bridge
volumes:
  postgres-data: { }
  redis-data: { }