# Generated by Django 4.2.3 on 2023-07-25 10:40

import apps.client.models
import django.core.validators
from django.db import migrations, models
import timezone_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('pk_id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('operator_code', models.CharField(help_text='Введите значение из 3 цифр.', max_length=3, validators=[apps.client.models.validate_three_digits])),
                ('phone_number', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(regex='^7\\d{9}$')])),
                ('tag', models.CharField(max_length=100)),
                ('timezone', timezone_field.fields.TimeZoneField(default='Europe/Moscow')),
            ],
        ),
    ]
