# Generated by Django 4.2.3 on 2023-07-25 10:59

import apps.client.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_client_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='operator_code',
            field=models.CharField(help_text='length of operator_code should be equal 3', max_length=3, validators=[apps.client.models.validate_three_digits]),
        ),
    ]
