# Generated by Django 4.2.3 on 2023-07-25 11:16

import apps.client.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_client_operator_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='operator_code',
            field=models.CharField(help_text='Введите значение из 3 цифр.', max_length=3, validators=[apps.client.models.validate_three_digits]),
        ),
    ]
