# Generated by Django 4.1.10 on 2023-07-25 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_alter_client_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
