# Generated by Django 4.1.10 on 2023-07-26 11:18

import apps.client.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_alter_client_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='operator_code',
            field=models.IntegerField(help_text='Введите значение из 3 цифр.', max_length=3, validators=[apps.client.models.validate_three_digits]),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.IntegerField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(regex='^7\\d{9}$')]),
        ),
    ]
