# Generated by Django 4.1.10 on 2023-07-26 11:20

import apps.client.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_alter_client_operator_code_alter_client_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='operator_code',
            field=models.IntegerField(help_text='Введите значение из 3 цифр.', validators=[apps.client.models.validate_three_digits]),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.IntegerField(unique=True, validators=[django.core.validators.RegexValidator(regex='^7\\d{9}$'), apps.client.models.validate_ten_digits]),
        ),
    ]
