# Generated by Django 4.1.10 on 2023-07-26 11:26

import apps.client.models
import apps.client.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_alter_client_operator_code_alter_client_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.IntegerField(unique=True, validators=[apps.client.validators.validate_starts_with_7, apps.client.models.validate_ten_digits]),
        ),
    ]
