# Generated by Django 4.1.10 on 2023-07-26 11:59

import apps.client.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_alter_client_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='operator_code',
            field=models.BigIntegerField(help_text='Введите значение из 3 цифр.', validators=[apps.client.validators.validate_three_digits]),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.IntegerField(unique=True, validators=[apps.client.validators.validate_starts_with_7]),
        ),
    ]
