# Generated by Django 4.2.3 on 2023-07-25 10:40

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('pk_id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(default=datetime.datetime(2023, 7, 25, 10, 40, 1, 889652, tzinfo=datetime.timezone.utc))),
                ('text', models.TextField()),
                ('filter', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('end_time', models.DateTimeField(default=datetime.datetime(2023, 7, 25, 10, 40, 1, 889687, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
