# Generated by Django 4.2.3 on 2023-07-25 10:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribution',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
