# Generated by Django 4.2.3 on 2023-07-25 11:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_client_operator_code'),
        ('distribution', '0002_alter_distribution_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('pk_id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('WAIT', 'Waiting'), ('ACTIVE', 'Active'), ('SUCCESS', 'Success'), ('EXPIRED', 'Expired')], default='WAIT', max_length=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='client.client')),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='distribution.distribution')),
            ],
        ),
    ]
