# Generated by Django 4.1.10 on 2023-07-26 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0004_alter_message_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('ERR', 'Error'), ('SUC', 'Success'), ('EXP', 'Expired')], default='ERR', max_length=10),
        ),
    ]
