# Generated by Django 4.1.10 on 2023-07-26 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_alter_client_operator_code_alter_client_phone_number'),
        ('distribution', '0006_alter_message_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='client.client'),
        ),
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('ERROR', 'Error'), ('SUCCESS', 'Success'), ('EXPIRED', 'Expired')], default='CREATED', max_length=10),
        ),
    ]
