# Generated by Django 4.1.10 on 2023-07-28 15:58

from django.db import migrations
import django_enum_choices.choice_builders
import django_enum_choices.fields
import other.enums


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0007_alter_message_client_alter_message_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('CREATED', 'CREATED'), ('ERROR', 'ERROR'), ('SUCCESS', 'SUCCESS'), ('EXPIRED', 'EXPIRED')], default=other.enums.Status['CREATED'], enum_class=other.enums.Status, max_length=7, verbose_name='Status'),
        ),
    ]
